version: '3.9'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_DATABASE=zolak-entry
    ports:
      - "127.0.0.1:3001:3001"
    networks:
      - zolak
    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo:latest
    networks:
      - zolak
    container_name: mongo-entry-svc
    hostname: mongo-entry-svc
    volumes:
      - mongo:/data/db
      - ./data:/dump
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.stats().ok' | mongosh localhost:27017/test --quiet"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    restart: unless-stopped

networks:
  zolak:
    name: zolak-entry

volumes:
  mongo:
    driver: local
    name: mongo-entry
